name: Alerts
title: Alerts
label: Alerts
status: wip
variants:
  - name: default
    label: Info
    context:
      alert:
        classes: "byu-alert--info"
        title: Informative status

  - name: success
    label: Success
    context:
      alert:
        classes: "byu-alert--success"
        title: Success status


  - name: warning
    label: Warning
    context:
      alert:
        classes: "byu-alert--warning"
        title: Warning status

  - name: error
    label: Error
    context:
      alert:
        classes: "byu-alert--error"
        title: Error status
        role: "alert"

  - name: no-header
    label: No header
    context:
      alert:
        classes: "byu-alert--info"
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."

  - name: no-icon
    label: No icon
    context:
      alert:
        classes: "byu-alert--info byu-alert--no-icon"
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."

  - name: slim
    label: Slim
    context:
      alert:
        classes: "byu-alert--info byu-alert--slim"
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."
