name: lines
title: Lines & Borders
label: Lines & Borders
collated: true
variants: 
  - name: default
    label: Horizontal Rule
    context:
      markupBefore: "<p>Horizontal rules have spacing above and below. They're a little darker than other borders and lines.</p>"
      markupAfter: "<p>Horizontal rules provide a distinct break between sections to indicate a change, such as a change in voice or thought.</p>"
  - name: table
    context:
      caption:
        data: 'Table borders follow the conventions for other borders and lines.'
        id: caption-id
      head:
        cells:
          - data: Heading&nbsp;1
          - data: Heading&nbsp;2
          - data: Heading&nbsp;3
          - data: Heading&nbsp;4
      rows:
        - cells:
            - data: Cell&nbsp;1.1
            - data: Cell&nbsp;1.2
            - data: Cell&nbsp;1.3
            - data: Cell&nbsp;1.4
        - cells:
            - data: Cell&nbsp;2.1
            - data: Cell&nbsp;2.2
            - data: Cell&nbsp;2.3
            - data: Cell&nbsp;2.4
        - cells:
            - data: Cell&nbsp;3.1
            - data: Cell&nbsp;3.2
            - data: Cell&nbsp;3.3
            - data: Cell&nbsp;3.4