name: article
title: Article
label: Article (typography test)
preview: "@preview--article"
status: wip
# hidden: true

variants:
  - name: default
    label: 'Open Sans'
    hidden: true
  - name: roboto
    label: 'Roboto'
    hidden: true
  - name: noto
    label: 'Noto Sans'