name: article
title: Article
label: Article
preview: "@preview--article"
status: wip

variants:
  - name: default
    label: 'Open Sans'
  - name: roboto
    label: 'Roboto'
  - name: noto
    label: 'Noto Sans'