name: header-styles
label: Styles
collated: true
status: wip

context: 
  title: Physical & Mathematical Sciences
  url: /
  actionBtn:
    url: //donate.byu.edu
    title: Donate
  search:
      action: /
      paramName: q
  byuID:
    username: pparker
  nav:
    - url: /
      title: Home
    - url: /about
      title: About
    - url: /programs
      title:  Majors & Programs
    - url: /students
      title: Students
    - url: /alumni
      title: Alumni
    - url: /giving
      title: Giving

variants:
  - name: default
    label: Default (Dark / Light)
    classes: "byu-header-dark byu-nav-light"
    context:
      byuID: null
      actionBtn: null
      title: Site name
  - name: default-full
    label: Default (with button and sign-in)
    classes: "byu-header-dark byu-nav-light"

  - name: light
    context:
      classes: "byu-header-light byu-nav-light"
      byuID: null
      actionBtn: null
      title: Site name
  - name: light-full
    label: Light (with button and sign-in)
    context: 
      classes: "byu-header-light byu-nav-light"

  - name: light-dark
    label: Light / Dark
    context:
      classes: "byu-header-light byu-nav-dark"
      byuID: null
      actionBtn: null
      title: Site name
  - name: light-dark-full
    label: Light / Dark (with button and sign-in)
    context: 
      classes: "byu-header-light byu-nav-dark"

  - name: dark
    context:
      classes: "byu-header-dark byu-nav-dark"
      byuID: null
      actionBtn: null
      title: Site name
  - name: dark-full
    label: Dark (with button and sign-in)
    context: 
      classes: "byu-header-dark byu-nav-dark"
