label: Buttons
status: wip
variants:
  - name: secondary
    context:
      category: alternate
      label: Secondary buttons
      classes: 'byu-button--secondary'

  - name: accent-cool
    context:
      category: alternate
      label: Accent cool buttons
      classes: 'byu-button--accent-cool'

  - name: base
    context:
      category: alternate
      label: Gray buttons
      classes: 'byu-button--base'

  - name: outline
    context:
      category: outline
      label: outline buttons
      classes: 'byu-button--outline'

  - name: outline-inverse
    context:
      category: outline-inverse
      label: outline inverse buttons
      classes: 'byu-button--outline byu-button--inverse'

  - name: big
    context:
      category: 'big'
      label: Big button
      classes: 'byu-button--big'

