name: page
title: Page
label: Page
status: wip
# hidden: true

context: 
  title: Marriott School
  url: /
  actionBtn: '@header--all.actionBtn'
  search: '@header--all.search'
  byuID: '@header--all.byuID'
  nav: '@header--all.nav'
